import { BusinessDomainConfig } from '../types';

export const BUSINESS_DOMAIN_PRESETS: Record<string, BusinessDomainConfig> = {
  generic: {
    domainKey: 'generic',
    domainName: 'Generic Operations',
    description: 'Standard operational workflows, task management, SLA tracking, and procedural compliance.',
    recordNounSingular: 'Operational Record',
    recordNounPlural: 'Operational Records',
    evidenceNoun: 'Completion Evidence',
    assigneeLabel: 'Owner',
    idPrefix: 'OP',
    reconciliationLabels: {
      primaryRecord: 'Operational Record',
      fulfilmentEvidence: 'Fulfilment Record',
      downstreamStatus: 'Downstream Status',
    },
    requiredFieldLabels: {
      customerName: 'Stakeholder / Client Name',
      contactPhone: 'Primary Contact Phone',
      destinationAddress: 'Destination / Target System',
      orderValue: 'Declared Value / Budget ($)',
      serviceCategory: 'Category / Priority Tier',
    },
    ruleDescriptions: {
      OVERDUE: 'Operational activity elapsed past target due date / SLA window.',
      MISSING_INFO: 'Mandatory operational metadata or required fields are omitted.',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when a case is recorded as completed but available fulfilment evidence or downstream status does not support completion.',
    },
  },
  logistics: {
    domainKey: 'logistics',
    domainName: 'Logistics & Order Fulfillment',
    description: 'Freight shipments, consignment dispatches, and proof of delivery verification.',
    recordNounSingular: 'Fulfillment Order',
    recordNounPlural: 'Fulfillment Orders',
    evidenceNoun: 'Proof of Delivery (POD) & Bill of Lading',
    assigneeLabel: 'Dispatch Agent',
    idPrefix: 'OP',
    reconciliationLabels: {
      primaryRecord: 'Dispatch Record',
      fulfilmentEvidence: 'Delivery Proof',
      downstreamStatus: 'Recipient Status',
    },
    requiredFieldLabels: {
      customerName: 'Consignee / Client Name',
      contactPhone: 'Delivery Contact Phone',
      destinationAddress: 'Delivery Address & Postal Code',
      orderValue: 'Declared Cargo Value ($)',
      serviceCategory: 'Freight Tier (Express/Standard)',
    },
    ruleDescriptions: {
      OVERDUE: 'Dispatch or transit elapsed past target delivery SLA window without delivery scan.',
      MISSING_INFO: 'Mandatory dispatch metadata (contact phone, delivery address, or consignee) is omitted.',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when dispatch is recorded as completed but recipient delivery proof is missing or recipient dock remains unconfirmed.',
    },
  },
  it_support: {
    domainKey: 'it_support',
    domainName: 'IT Support & Service Management',
    description: 'Enterprise incident tickets, change requests, and SLA resolution tracking.',
    recordNounSingular: 'Incident Ticket',
    recordNounPlural: 'Incident Tickets',
    evidenceNoun: 'Root Cause Analysis & User Sign-off',
    assigneeLabel: 'Support Engineer',
    idPrefix: 'INC',
    reconciliationLabels: {
      primaryRecord: 'Incident Record',
      fulfilmentEvidence: 'Fix Evidence',
      downstreamStatus: 'Monitoring Status',
    },
    requiredFieldLabels: {
      customerName: 'Reporting User / Employee',
      contactPhone: 'Callback Extension / Phone',
      destinationAddress: 'Affected System / Workstation ID',
      orderValue: 'Service Impact Score (1-5)',
      serviceCategory: 'Infrastructure Component',
    },
    ruleDescriptions: {
      OVERDUE: 'Ticket resolution time exceeded defined SLA response/resolution tier.',
      MISSING_INFO: 'Missing critical troubleshooting metadata (system ID, caller contact, or severity).',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when ticket is marked resolved but fix diagnostic proof is missing or system telemetry remains unresolved.',
    },
  },
  real_estate: {
    domainKey: 'real_estate',
    domainName: 'Real Estate & Property Closing',
    description: 'Property escrow transactions, leasing contracts, and legal due diligence.',
    recordNounSingular: 'Closing File',
    recordNounPlural: 'Closing Files',
    evidenceNoun: 'Escrow Receipt & Executed Deed/Lease',
    assigneeLabel: 'Closing Officer',
    idPrefix: 'RE',
    reconciliationLabels: {
      primaryRecord: 'Service Request',
      fulfilmentEvidence: 'Vendor Work Order',
      downstreamStatus: 'Tenant Confirmation',
    },
    requiredFieldLabels: {
      customerName: 'Buyer / Lessee Name',
      contactPhone: 'Primary Contact Phone',
      destinationAddress: 'Parcel Address & Unit Number',
      orderValue: 'Contract Transaction Value ($)',
      serviceCategory: 'Property Asset Class',
    },
    ruleDescriptions: {
      OVERDUE: 'Closing contingency or statutory escrow milestone past closing deadline.',
      MISSING_INFO: 'Required title or identification fields absent from closing packet.',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when transaction is marked closed but settlement/vendor proof is missing or tenant confirmation is unconfirmed.',
    },
  },
  hospitality: {
    domainKey: 'hospitality',
    domainName: 'Hospitality & Facility Operations',
    description: 'Guest room maintenance, VIP requests, and housekeeping turnover inspection.',
    recordNounSingular: 'Service Request',
    recordNounPlural: 'Service Requests',
    evidenceNoun: 'QA Inspection Sign-off & Room Photo',
    assigneeLabel: 'Facility Lead',
    idPrefix: 'HOS',
    reconciliationLabels: {
      primaryRecord: 'Guest Request',
      fulfilmentEvidence: 'Service Completion',
      downstreamStatus: 'Guest Confirmation',
    },
    requiredFieldLabels: {
      customerName: 'Guest Name / VIP ID',
      contactPhone: 'Room Extension / Mobile',
      destinationAddress: 'Room / Suite / Banquet Hall',
      orderValue: 'Work Order Cost Estimate ($)',
      serviceCategory: 'Service Type (HVAC/Cleaning/Catering)',
    },
    ruleDescriptions: {
      OVERDUE: 'Service turnaround duration exceeded guest promise or housekeeping SLA.',
      MISSING_INFO: 'Request logged without room location or guest identity information.',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when guest service is marked complete but photo/QA evidence is missing or guest status is unresolved.',
    },
  },
  recruitment: {
    domainKey: 'recruitment',
    domainName: 'Recruitment & Candidate Onboarding',
    description: 'Talent hiring pipelines, offer letter acceptances, and credential compliance.',
    recordNounSingular: 'Onboarding Case',
    recordNounPlural: 'Onboarding Cases',
    evidenceNoun: 'Signed Offer Letter & Background Clearance',
    assigneeLabel: 'Talent Partner',
    idPrefix: 'REC',
    reconciliationLabels: {
      primaryRecord: 'Onboarding Case',
      fulfilmentEvidence: 'Signed Contract / Verification',
      downstreamStatus: 'Department Intake Status',
    },
    requiredFieldLabels: {
      customerName: 'Candidate Full Name',
      contactPhone: 'Candidate Phone',
      destinationAddress: 'Assigned Office / Remote Workstation',
      orderValue: 'Starting Compensation ($)',
      serviceCategory: 'Hiring Department & Level',
    },
    ruleDescriptions: {
      OVERDUE: 'Target start date pending with prerequisite compliance tasks incomplete.',
      MISSING_INFO: 'Candidate file lacks critical contact details or tax/legal jurisdiction.',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when onboarding is marked completed but signed contract is missing or department intake is unconfirmed.',
    },
  },
  ecommerce: {
    domainKey: 'ecommerce',
    domainName: 'E-Commerce RMA & Returns Processing',
    description: 'Customer return merchandise authorizations, warehouse restock, and refund validation.',
    recordNounSingular: 'RMA Return Order',
    recordNounPlural: 'RMA Return Orders',
    evidenceNoun: 'Warehouse Barcode Scan & Condition Audit',
    assigneeLabel: 'Returns Inspector',
    idPrefix: 'RMA',
    reconciliationLabels: {
      primaryRecord: 'RMA Return Order',
      fulfilmentEvidence: 'Warehouse Inspection',
      downstreamStatus: 'Restock / Refund Status',
    },
    requiredFieldLabels: {
      customerName: 'Customer Name',
      contactPhone: 'Customer Phone',
      destinationAddress: 'Return Transit Hub / Warehouse Bay',
      orderValue: 'Refund Item Value ($)',
      serviceCategory: 'Merchandise Category',
    },
    ruleDescriptions: {
      OVERDUE: 'Return package received at dock but inspection exceeds 48-hour SLA.',
      MISSING_INFO: 'Return request missing original order ID or customer contact.',
      COMPLETED_WITHOUT_EVIDENCE: 'A Status–Outcome Conflict exists when return is marked completed but warehouse inspection is missing or restock/refund is unresolved.',
    },
  },
};

export const DEFAULT_DOMAIN_KEY = 'generic';

export const REQUIRED_FIELD_KEYS = [
  'customerName',
  'contactPhone',
  'destinationAddress',
  'orderValue',
  'serviceCategory',
];
